# Generated by Django 5.0.6 on 2025-10-27 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text='Optional - can be auto-calculated from date_of_birth', null=True)),
                ('height_feet', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_inches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('alternate_mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('instagram_profile', models.URLField(blank=True)),
                ('native_state', models.CharField(blank=True, max_length=100)),
                ('current_state', models.CharField(blank=True, max_length=100)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='documents/aadhar/')),
                ('close_up_photo', models.ImageField(blank=True, null=True, upload_to='photos/close_up/')),
                ('full_length_photo', models.ImageField(blank=True, null=True, upload_to='photos/full_length/')),
                ('mid_length_photo', models.ImageField(blank=True, null=True, upload_to='photos/mid_length/')),
                ('natural_look_photo', models.ImageField(blank=True, null=True, upload_to='photos/natural_look/')),
                ('natural_look_makeup_photo', models.ImageField(blank=True, null=True, upload_to='photos/natural_look_makeup/')),
                ('how_did_you_hear', models.CharField(blank=True, help_text='e.g., Social Media, Friend, Advertisement', max_length=250)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=999.0, max_digits=8)),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
